export const clientsList = [
  { clientName: "Adobe Lightroom", clientCategory: "art", clientLink: "https://www.adobe.com/products/photoshop-lightroom.html" },
  { clientName: "Andie Swim", clientCategory: "fashion", clientLink: "https://www.andieswim.com/" },
  { clientName: "Anna Jean Kos", clientCategory: "fashion", clientLink: "https://annajeankos.com" },
  { clientName: "Arvo Cafe", clientCategory: "food", clientLink: "https://www.arvocafe.com/" },
  // { clientName: "Asics", clientCategory: "fashion", clientLink: "https://www.asics.com/" },
  { clientName: "ASOS", clientCategory: "fashion", clientLink: "https://www.asos.com/" },
  { clientName: "AVVA Brand", clientCategory: "fashion", clientLink: "https://avvabrand.com/" },
  { clientName: "Banan", clientCategory: "food", clientLink: "https://banan.co/" },
  { clientName: "BLKCORAL", clientCategory: "art", clientLink: "https://www.blkcoral.com/" },
  { clientName: "Darling NYC", clientCategory: "food", clientLink: "https://www.parklanenewyork.com/dine/darling-rooftop/" },
  { clientName: "Fiberworkshop", clientCategory: "fashion", clientLink: "https://fiberworkshop.com/" },
  { clientName: "Hawai'i Theatre", clientCategory: "art", clientLink: "https://www.hawaiitheatre.com/" },
  { clientName: "Hawaiian Airlines", clientCategory: "hotel", clientLink: "https://www.hawaiianairlines.com/" },
  { clientName: "Honolulu Pawn Shop", clientCategory: "fashion", clientLink: "https://honolulupawnshop.com/" },
  { clientName: "Honolulu Volkswagen", clientCategory: "other", clientLink: "https://www.honoluluvw.com/" },

  { clientName: "Jams World", clientCategory: "fashion", clientLink: "https://www.jamsworld.com/" },
  { clientName: "Kaimana Beach Hotel", clientCategory: "hotel", clientLink: "https://www.kaimana.com/" },
  { clientName: "Kapolei Commons", clientCategory: "food", clientLink: "https://kapoleicommons.com/" },
  // { clientName: "Kona Brewing", clientCategory: "food", clientLink: "https://konabrewingco.com/" },
  { clientName: "Live Nation", clientCategory: "art", clientLink: "https://www.livenation.com/" },
  { clientName: "Live Nation Comedy", clientCategory: "art", clientLink: "https://www.livenation.com/comedy/" },
  {clientName: "Lō'ihi Records", clientCategory: "art", clientLink: "https://loihirecords.com/"},
  { clientName: "Marie Claire UK", clientCategory: "fashion", clientLink: "https://www.marieclaire.co.uk/" },
  { clientName: "M3N3HUN3", clientCategory: "fashion", clientLink: "https://m3n3hun3.com/" },
  { clientName: "Milo", clientCategory: "fashion", clientLink: "https://www.instagram.com/milohawaii/?hl=en" },
  { clientName: "Oak St Productions", clientCategory: "art", clientLink: "https://oakstproductions.com" },
  // { clientName: "OluKai", clientCategory: "fashion", clientLink: "https://olukai.com/" },
  { clientName: "Pepperblack Studios", clientCategory: "art", clientLink: "http://www.pepperblackstudios.com/" },
  { clientName: "Portal Agency Tokyo", clientCategory: "art", clientLink: "https://ponocollective.org/" },
  { clientName: "Pono Collective Coffee", clientCategory: "food", clientLink: "https://www.portalagency.net/" },
  { clientName: "POW! WOW! Worldwide", clientCategory: "art", clientLink: "https://www.powwowworldwide.com/" },
  { clientName: "Rip Curl", clientCategory: "fashion", clientLink: "https://www.ripcurl.com/us/" },
  // { clientName: "Roark", clientCategory: "fashion", clientLink: "https://www.roark.com/" },
  { clientName: "Rowing Blazers", clientCategory: "fashion", clientLink: "https://www.rowingblazers.com/" },
  { clientName: "Roxy", clientCategory: "fashion", clientLink: "https://www.roxy.com/" },
  { clientName: "Savor Brands", clientCategory: "other", clientLink: "https://savorbrands.com/" },
  { clientName: "Sea Room Lynn", clientCategory: "fashion", clientLink: "https://searoomlynn.jp/" },
  { clientName: "Servco Subaru", clientCategory: "other", clientLink: "https://www.servcosubaru.com/" },
  { clientName: "Skycar Creative", clientCategory: "art", clientLink: "https://www.skycar.tv/" },
  { clientName: "Specialty Coffee Association", clientCategory: "food", clientLink: "https://sca.coffee/" },
  // { clientName: "Stab", clientCategory: "other", clientLink: "https://stabmag.com/" },
  { clientName: "Stone Fox Swim", clientCategory: "fashion", clientLink: "https://stonefoxswim.com/" },
  { clientName: "Surf Camp Coffee", clientCategory: "food", clientLink: "https://surfcampshop.com/" },
  { clientName: "Surfjack Hotel & Swim Club", clientCategory: "hotel", clientLink: "https://www.surfjack.com/" },
  { clientName: "Sustainable Coastlines Hawai'i", clientCategory: "other", clientLink: "https://www.sustainablecoastlineshawaii.org/" },
  { clientName: "Toast Swim", clientCategory: "fashion", clientLink: "https://www.toastswim.com/" },
  { clientName: "Towa", clientCategory: "fashion", clientLink: "https://towaclothing.com/" },
  { clientName: "Urban Outfitters UK", clientCategory: "fashion", clientLink: "https://www.urbanoutfitters.com/en-gb/" },
  // { clientName: "Vissla", clientCategory: "fashion", clientLink: "https://www.vissla.com/" },
  { clientName: "Wayfinder Hotel Waikiki", clientCategory: "hotel", clientLink: "https://www.wayfinderhotels.com/waikiki/" },
  { clientName: "World Surf League", clientCategory: "other", clientLink: "https://www.worldsurfleague.com/" }
];
